- name: install nginx
  become: yes
  yum: name=nginx
     state=latest
  notify: Restart nginx

- name : copy nginx configs to {{nginx_port}}
  become: yes
  template:
    src: nginx.conf
    dest: /etc/nginx/conf.d/default.conf
  notify: Restart nginx



- name: start nginx
  become: yes
  service:
    name: nginx
    state: started
    enabled: yes
