---
  - hosts: webserver1
    vars_files:
      - ./configs/webserver1.yml
    roles:
      - webserver1

  - hosts: webserver2
    vars_files:
      - ./configs/webserver2.yml
    roles:
      - webserver2
