---
  - hosts: webserver1
    vars_files:
      - ./configs/webserver1.yml
    roles:
      - nodejs
      - nginx

  - hosts: webserver2
    vars_files:
      - ./configs/webserver2.yml
    roles:
      - nodejs
